### ISSUE TITLE
Mention that it’s deprecated on npmjs.com

### ISSUE THREAD

**Issue by tomek-he-him** [rollup/rollup-babel#27]
I only know that it’s deprecated because I was feeling adventurous and did https://github.com/search?q=rollup-babel.

There’s two ways to let people know:
#### 1

``` sh
npm deprecate rollup-babel
```

  – `npm install rollup-babel` will then print a warning.
#### 2

``` sh
npm version patch && npm publish
```

  – then the readme at http://npm.im/rollup-babel will say the same as the readme at github.

**Comment by Rich-Harris** [comment]
Thanks! Have done both of those things
