### ISSUE TITLE
`rollupbabel` vs. `rollup-babel`

### ISSUE THREAD

**Issue by Victorystick** [rollup/rollup-babel#6]
Why is the CLI tool named `rollupbabel` and not `rollup-babel` like the repository?
The [readme has to explain](https://github.com/rollup/rollup-babel#usage) to use `rollup-babel` from scripts and `rollupbabel` from the terminal.

Wouldn't it be easier to just always go for `rollup-babel`? Any reason I'm unaware of?

**Comment by Rich-Harris** [comment]
Yeah, not quite sure what I was thinking. Though I don't think we should worry about it – I think we should deprecate this repo and figure out the correct plugin architecture instead, as per https://github.com/rollup/rollup/issues/178. That way there's no need for a proliferation of wrapper projects (grunt-rollup-babel, gobble-rollup-babel, gulp-rollup-babel)

**Comment by Victorystick** [comment]
Also true. Well, I look forward to a busy discussion concerning plugins then.
